### ISSUE TITLE
Recepies which can be cooked should be first in the list.

### ISSUE THREAD

**Issue by Spexify** [Spexify/emergenCity#108]

**Comment by Micky1503** [comment]
From the userstudy to that: "Die Rezepte, die nicht zubereitet werden können sind ausgegraut. Könnte man diese auch nicht anzeigen?" -> The users where annoyed by so many not-cookable recipes. Sorting them could help.

**Comment by marCOmics** [comment]
Agreed, maybe you can do it with the help of @Spexify, @Micky1503? I don't have a good idea of the top of my head for an optimal algorithm, but @Spexify already used a cool way of sorting in the inventoryGUI, and you code-reviewed the code recently so maybe the two of you can work it out. ^^ In my opinion, it's only nice to have, so no problem if you don't get to do it.
