### ISSUE TITLE
Better scrolling

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#109]
Scrolling in e.g. the character choice or in the scrollable text containers (e.g. in the end-of-game-summary) right now only work through the small scroll bar at the right. Should work the same as for the cooking GUI, so that you can just scroll "on the items".

**Comment by Micky1503** [comment]
Cite: "scrollen ist die wahre Krise" :D

**Comment by marCOmics** [comment]
already done with previous issues!
