### ISSUE TITLE
"Umlaute" for normal font

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#111]
The normal font does not include "Umlaute" (äöü), which makes the text look weird.

**Comment by Micky1503** [comment]
Adding to that: "G und H der verwendeten Schriftart sind etwas schwierig zu lesen."

**Comment by Micky1503** [comment]
"Die Schrift ist etwas schwierig zu lesen und kann immernoch keine Umlaute richtig darstellen." -> Could we maybe change the font for another? Are there any better options?

**Comment by marCOmics** [comment]
Was also mentioned in Zulip Feedback channel

**Comment by Spexify** [comment]
Changed font in 3b6349b7c5115edf20b864a93dad04838edd11ff
