### ISSUE TITLE
Citymap: Make clickable places more noticable through shaders

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#112]
It is not clear which places on the world map are clickable/enterable. Maybe the places should have a bigger frame around them, or colored lighter than the rest, etc. 
Also, the "closed" sign on the shop is not well readable (less readable than the "Shop"-sign, so people could try to click on that).

**Comment by Micky1503** [comment]
Another possibility to highlight enterable places could be adding more "pins" like the one for home.

**Comment by marCOmics** [comment]
> Another possibility to highlight enterable places could be adding more "pins" like the one for home.

We already had discussed this with the AG, but my concern was, that having pins at every location you can enter is WAY to much visual chaos and defeats the purpose of the pins (attracting attention only works with a single or few pins).

I think the best solution is the shader-one, that we talked about with everybody
