### ISSUE TITLE
Pausing the game when PopUps are open

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#114]
"Manchmal habe ich auf ein Objekt z.b. das Bett gedrückt ohne dass etwas passiert ist, weil noch eine andere Aktion geöffnet war und sich diese nur durch drücken auf Abbruch schließen lässt." -> Possible solution: Pausing the game when PopUps are open, like for new crisis, optional events, other actions, etc.

**Comment by Micky1503** [comment]
On the other hand, another user writes: "Was mich gestört hat ist, dass wenn man z.B. in der Wohnung den Fernseher anklickt hat und die Information eingeblendet wurde, man erstmal auf "zurück" klicken musste, um sich weiter in der Wohnung zu bewegen, statt dass die Einblendung einfach verschwindet"

**Comment by marCOmics** [comment]
We decided as a group: The game should be paused, you should first have decide before you can interact with sth.
-> Solve overlapping, see other issue.
