### ISSUE TITLE
Shop: Possibility to remove only single items, not only all items at once by going on "Abbrechen"

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#118]
"Im Shop können Items nur durch abbrechen wieder entfernt werden, durch anklicken des Items wäre es deutlich einfacher."

**Comment by Spexify** [comment]
Items can be removed by pressing on them. There was a small bug in the UserStudy where the first three items bought could not be removed. Thats probably where this Feedback comes from.
