### ISSUE TITLE
AVATAR navigation ignores Collision objects in its way

### ISSUE THREAD

**Issue by marCOmics** [Spexify/emergenCity#12]
Todo: Remove Navigation Layer in ready() for tiles that have Collision on any (!) layer.

**Comment by marCOmics** [comment]
Collision with tiles fixed, only NPCs stand in the way now

**Comment by marCOmics** [comment]
Note: I had tried to fix this with an NavigationObstacle2D node, but it didn't work in the way I planned. Also, because the NPCs can't move and we can place them apart from each other so the don't build a wall, this can be worked around.

**Comment by Spexify** [comment]
If fixed this in commits f4d82c2af2411c31dcaf78f16b5a92fdc1f46069 and fa963e39d38a9818c838769ed19fd6364ecfd796. When spawning a NPC the nvigation tile map will be updated to exclude tiles where NPCs stand.
