### ISSUE TITLE
Balancing: Do not allow 1-day-crisis

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#122]
"Ich habe die Krise nach 1 Tag überstanden und gewonnen, ziemlich einfach ohne das Spiel wirklich verstanden zu haben" -> After only one day the player can not lose, no matter what they did on that day. That should maybe not be possible.

**Comment by cccynic** [comment]
refactor to start at 3

**Comment by cccynic** [comment]
done
