### ISSUE TITLE
Inform player about all icons in Tutorial

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#123]
At the moment, one action is consumed when cooking (as intended), but the player is not informed of that before cooking.

-> EDITED: We want to have a screen after the tutorial that has a short explanation about all icons in the game.

**Comment by marCOmics** [comment]
Idea: Add "needs_time" icon to button

**Comment by oFabritz** [comment]
Yes i agree that the icon is sufficient. Although we should probably explain the concept of time and this icon in more detail

**Comment by cccynic** [comment]
4 vitals, time icons, needs water and electricity, states of house/crisis in the pause menu

**Comment by cccynic** [comment]
done
