### ISSUE TITLE
End-of-day: Adjust textbox and/or fontsize

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#124]
"Das Format von der Tagesübersicht funktioniert immernoch nicht sauber, weil die Tageszeiten und die Einträge dafür nicht aligned sind."

**Comment by marCOmics** [comment]
Solution idea: In the node hierarchy you first need to have VBoxContainers and then HBoxContainers, instead of the other way around

**Comment by cccynic** [comment]
done, untested
