### ISSUE TITLE
Bug/Ambiguity of difficulty setting

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#129]
"Die Schwierigkeits-Auswahl finde ich auch sehr sinnvoll, allerdings konnte ich keine davon auswählen und hab daher immer nur den einfachen Modus gespielt. Vielleicht ist das aber auch so gewollt und man kann den Modus selber nicht ändern? Ich konnte nämlich immer nur auf "weiter" klicken." -> This is either a bug, or the person did not understand the slider under the difficulties. Would it be possible to also make the words themselves ("Kurz"/"Mittel"/"Lang") clickable and change the slider accordingly when the word is clicked?

**Comment by marCOmics** [comment]
Related: #86

**Comment by cccynic** [comment]
done
