### ISSUE TITLE
New sounds after actions (like tapping water or cooking)

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#131]
"würde mir nach Aktivitäten (zbsp Wasser zapfen) ein Geräusch/Text wünschen, der bestätigt das die Aktion funktioniert hat" -> probably better sounds than text because thats one less thing to click "weiter" on; could also be used for cooking

**Comment by marCOmics** [comment]
I also proposed that!
My wishlist for SFX in actions:
* Cooking
* Shower 
* Tap water
* Change stage
* Sleep

And also for consume-interactions in the SEOD:
* Eat
* Dring
* Filter
* (a general use soundeffect for all the other ones)

The soundeffects don't have to be produced by us, we can use royalty-free soundeffects and add the license to the folder.

**Comment by marCOmics** [comment]
Related: #23

**Comment by Spexify** [comment]
You can now and sounds to actions via json
