### ISSUE TITLE
Hide double non-cookable recipes

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#133]
"Im Kochmenü werden manche Rezepte mehrfach angezeigt weil sie mit unterschiedlichen Zutaten zubereitet werden können. Das macht das Menü insgesamt etwas unübersichtlich." -> Non-cookables are not selectable anyway, so you do not see which ingredients you need. So maybe we could just hide all but one non-cookable recipes with the same name?

**Comment by marCOmics** [comment]
Makes sense, if you have time, you can look into that :)
