### ISSUE TITLE
Displaying an error message when inventary is full

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#134]
"Es ist möglich das Inventar komplett mit Wasserflaschen aufzufüllen, es gibt auch keine Fehlermeldung wenn das Inventar überfüllt wird."

**Comment by marCOmics** [comment]
Good point. :o

**Comment by marCOmics** [comment]
Didn't fix it perfectly (inside the inventory class itself) but for the action consequence methods. Should do the job for most cases ^^
