### ISSUE TITLE
Water spoils after one day

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#135]
"Haltbarkeit von Wasser macht hier zwar spielerisch Sinn, aber nach einem Tag schon sehr schnell verdorben" -> Should not spoil at all, right?

**Comment by marCOmics** [comment]
I just checked, water doesn't have a shelflive component, so it should never spoil like you said! We have to look into that, if there's a bug.

**Comment by Micky1503** [comment]
Related to that: "Ich fühle mich betrogen, wenn mein abgefülltes Wasser und meine Konserven verderben, nur weil an Tag 2 kein sauberes Wasser mehr aus der Leitung kommt. Wie soll Vorbereitung mir denn so wertvoll vorkommen? Aber interessant, dass ein Kochen der ungenießbaren Nudeln dann doch zu einem genießbaren Produkt führt. War das so intendiert? Wenn ja, sollte ich, finde ich, auch in der Lage sein, die gekochten Produkte noch einmal zu erwärmen und so die Erreger abzutöten; andernfalls habe ich völlig umsonst meine Zeit des ersten Tages in Meal Prep gesteckt. Andererseits hat sich bei einer weiteren Partie auch der Status des Nudelgerichts als „verdorben“ gehalten; merkwürdig."

'Konserven' should also not spoil, right? And spoiled food should not be usable for cooking, right? Some things seem to work weird for the spoiling-feature.

**Comment by cccynic** [comment]
done
