### ISSUE TITLE
!!! Game crashes if you close it whole the SEOD is open

### ISSUE THREAD

**Issue by marCOmics** [Spexify/emergenCity#146]
If you play the game and close the application while the SEOD is opened, it crashes and **deletes** the savegame AND savestate!!
![image](https://github.com/Spexify/emergenCity/assets/48869977/43f1341f-98e4-449c-b69d-01e70654d39b)

The problem is related to the saving mechanic as you can see from the screenshots.
Big bug, needs to be fixed at all costs.

**Comment by Spexify** [comment]
This only had something to do with saving after a stage change, Is know fixed
