### ISSUE TITLE
Dialogue and pop up event collision

### ISSUE THREAD

**Issue by cccynic** [Spexify/emergenCity#153]
![image](https://github.com/Spexify/emergenCity/assets/103509027/ff18b799-903a-47f0-ae63-4c2ae3026809)

**Comment by marCOmics** [comment]
Solution idea:
* define new signal when dialoge ends in crisis phase
* emit the signal dialogue
* use `await _crisis_phase.<newsignalname>` in the method of the day manager when the time progresses.

If that doesn't work, move the dialogue execute-lines to the end of the dialogue

**Comment by marCOmics** [comment]
done
