### ISSUE TITLE
SEOD: Shade unconsumable items darker

### ISSUE THREAD

**Issue by marCOmics** [Spexify/emergenCity#25]
The modulation of the items in the inventory gui should be set to a darker tone for all items that aren't consumable.
This way the user instinctivly knows which items he can consume.
Maybe also deactivate clicking on items that aren't consumable.

**Comment by marCOmics** [comment]
Won't fix (see Comment in Code of inventory_GUI.gd

**Comment by Spexify** [comment]
I do not think shading the items is nessesary.
