### ISSUE TITLE
Shop: Buying Items doesn't work

### ISSUE THREAD

**Issue by marCOmics** [Spexify/emergenCity#28]
When you buy items on the exported version on Android, the items don't get transferred to the inventory.
(Maybe a savestate issue on mobile?)

**Comment by Spexify** [comment]
Savestate is probably not the problem, the only save game related function tiggered in between crisis and prepare Phase is reset_state which does not contain the inventory.

For me this bug (or a similar bug) occurese on PC and Mobile only in the second PreparePhase if I buy new Items and have prior consumed items in the CrisisPhase. If you dont buy new items an Error Item will appear in the next CrisisPhase in the places where you consumed items in the prior CrisisPhase. So my guess is that item consumtion/discard in the Inventory_Gui my cause this problem.

**Comment by marCOmics** [comment]
-> Also: Reset inventory after a crisis is finished

**Comment by Spexify** [comment]
Should be fixed by recent commit cd42433, the inventory will be reset after each crisis Phase and Reset button.
