### ISSUE TITLE
Game breaks after starting crisis phase a second time.

### ISSUE THREAD

**Issue by Spexify** [Spexify/emergenCity#46]
I didn't have much time to troughtly check but it occures because Settings is now as Global singelton and after scene stage holds refrences to no existing objects.

**Comment by marCOmics** [comment]
pause menu reference has to be reset?

**Comment by marCOmics** [comment]
-> Also happens when you cancel the crisis

**Comment by Spexify** [comment]
Added a new function which calls settings without signal to prevent call to an unitialized pause_menu.
