### ISSUE TITLE
The Endscreen is visually bugged

### ISSUE THREAD

**Issue by marCOmics** [Spexify/emergenCity#51]
The endscreen doesn't display the proper descriptions of the actions anymore:
![4b566c09-64c7-45dd-a528-bcfe85e74d0a](https://github.com/Spexify/emergenCity/assets/48869977/d076fc2d-fae7-462d-a75e-6ba9bdb8bc46)

Furthermore the text is weirdly indented/framed and spills out of its container.

**Comment by marCOmics** [comment]
(Maybe a scroll container has a too big width?)

**Comment by cccynic** [comment]
bug fixed
