### ISSUE TITLE
CookingGUI crash probably caused by InventiryGUI

### ISSUE THREAD

**Issue by cccynic** [Spexify/emergenCity#52]
tried to cook, got given the following error
![WhatsApp Image 2024-02-17 at 14 03 06_36c4c331](https://github.com/Spexify/emergenCity/assets/103509027/3014ecd1-aceb-48f2-967a-b41bb5934d41)

**Comment by marCOmics** [comment]
I coudln't reproduce the error :( Maybe we have to look into it tomorrow, if you're here in person.

**Comment by marCOmics** [comment]
Karina solved it

**Comment by marCOmics** [comment]
closed
