### ISSUE TITLE
Small Animation when the statusbars are updated

### ISSUE THREAD

**Issue by marCOmics** [Spexify/emergenCity#55]
- Slowly raise the bar
- Add icon and changed-amount above avatar or in the middle of the screen or below the status bars and fade them away
- (maybe also particles)

**Comment by marCOmics** [comment]
Slowly changing bar could be implemented in process-func (like explained here https://forum.godotengine.org/t/how-to-decrease-the-value-of-the-progressbar-automatically-and-slowly/21974), but additional temporary variables would be needed.
Not worth the effort rn

The particles were already done in #158

**Comment by Spexify** [comment]
Did this with shaders in 7e4651a903fbf5f4e23cb3351f54801d17927512
