### ISSUE TITLE
Popups shown simultaneosuly

### ISSUE THREAD

**Issue by cccynic** [Spexify/emergenCity#57]
some popups shown overlapping and multiple guis at the same time

**Comment by marCOmics** [comment]
SEOD, Endgame, Optional Events, Popup Events, Action GUI (like Rest?)?
-> Solution: Wait for one GUI to be closed, before opening the next one

**Comment by marCOmics** [comment]
Reopened as discuessed

**Comment by marCOmics** [comment]
I have a cool idea how to fix this! :)

**Comment by marCOmics** [comment]
-> Only collision that's still possible now should be Optional Events (Rain) + Popup Events
