### ISSUE TITLE
After multiple stage changes in the city, the home stage bugs

### ISSUE THREAD

**Issue by cccynic** [Spexify/emergenCity#58]
![image](https://github.com/Spexify/emergenCity/assets/103509027/c3f508c9-58f7-4a6f-909b-e7c6169d9a2a)

I can move, open gus, but not click on buttons.

**Comment by marCOmics** [comment]
fixed that some while ago

**Comment by marCOmics** [comment]
(solution: make sure the animation always plays, not only when paused)
