### ISSUE TITLE
Inventory GUI doesn't show Items from Inventory correctly

### ISSUE THREAD

**Issue by cccynic** [Spexify/emergenCity#62]
I filtered water with the chlor tablette. Had 2 bottles dirty water, got 2 bottles clean water, but the only one dirty water bottle was visually removed. After getting the message there is no more dirty water to filter (which was correct), there was still a bottle of dirty water shown. When clicking on it, I was not shown any components.
![image](https://github.com/Spexify/emergenCity/assets/103509027/2c8c8cfd-f039-4a24-9743-56c393be31cc)

**Comment by marCOmics** [comment]
Jakob, you did some changes, hopefully once you push them they are fixed. Please check that and close the issue if its ok ^^
