### ISSUE TITLE
SEOD GUI: Combine action-overview with first GUI

### ISSUE THREAD

**Issue by marCOmics** [Spexify/emergenCity#67]
The first GUI is pretty empty and the process has many GUIs:
![image](https://github.com/Spexify/emergenCity/assets/48869977/05343a3c-a096-41a4-ab51-9a69253fc008)

To improve the UX, the clicks should be minimized. For that we can combine the overview of the day with the text of the first GUI.
So when a day ends, two GUIs should appear:
1. The overview of what actions the player did, but now with the prompt "Kümmer dich...".
2. The inventory as usual.

ALTERNATIVE IDEA:
1. The inventory, but change the title text to the prompt "Kümmer dich.."
2. The overview of the day, as before

**Comment by cccynic** [comment]
closed
