### ISSUE TITLE
Multiple back buttons in button list: Older back buttons stop working

### ISSUE THREAD

**Issue by marCOmics** [Spexify/emergenCity#71]
If you enter the citymap and then open the backpack, the first time you use the back button it works properly and closes the backpack, but the second press doesn't close the citymap .. :(

**Comment by marCOmics** [comment]
We don't have a usecase where two GUIs simultaneously can be opened that use the button-list-back-button feature, so it's really not urgent

**Comment by Spexify** [comment]
Fixed with gui_mngr add85427cff826fc66c9d02c914d530eef1cbf4e
