### ISSUE TITLE
Hygiene sinkt random

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#74]
Wenn ich ein neues Spiel starte, starte ich mit 100% Hygiene. Wenn ich mich einmal ausruhe, sinkt die Hygiene auf 50%. Mit jedem Ausruhen steigt die Hygiene wieder um 10%. Sie sinkt nicht wieder.
1.) Das Sinken auf 50% ist ein Bug, richtig? Muss dementsprechend gefixt werden.
2.) Das Um-10%-erhöhen ist noch ein Relikt aus der Vergangenheit, als es das Duschen noch nicht gab. Kann entfernt werden.
3.) Am Ende des Tages muss die Hygiene-Bar wieder sinken (wie auch Essen und Trinken), tut sie im Moment nicht.

**Comment by cccynic** [comment]
1) is a bug also with the happiness bar
2) I thought we are keeping it, will correct that - no probs
3) will be done

**Comment by cccynic** [comment]
2) and 3) are done

**Comment by cccynic** [comment]
1) also fixed
