### ISSUE TITLE
Event (wahrscheinlich Merts) bricht ab

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#80]
Manchmal wird nach dem PopUp-Event-Klopfen, wenn man auf Bestätigen geht, danach nicht der Dialog gestartet, sondern das Spiel bricht ab. Erklärung von godot: In dialogue_GUI.gd wird für die Variable dialogue_line auf die childs von response_menu zugegriffen; dies scheint aber ein null value zu sein, d.h. get_children funktioniert nicht auf response_menu.

Vermutlich passiert das bei Merts Event, denn alle anderen sind erfolgreich beim Testen aufgetreten. Merts Event ist das einzige, das den constraint no_clean_water_available nutzt; vielleicht liegt es daran?

**Comment by marCOmics** [comment]
Hab versucht es zu fixen, indem ich u.a. eine Abfrage auf null mache an der Stelle im Code. Also hab mal testweise den constraint weg genommen (da es sonst einfach unwahrscheinlicher ist dass alle constraints erfüllt sind), dann funktioniert es. Kann aber nicht sagen, ob das Problem wirklich behoben ist. Evtl. liegt es auch nicht unbedingt an Mert's Event, sondern einer bestimmten Konstellation. Schwierig zu reproduzieren leider. :s

**Comment by marCOmics** [comment]
Ich schließe es mal "vorsichtig", falls es doch noch mal auftritt, müssen wir uns das anschauen.
