### ISSUE TITLE
Cooking without electricity - Not clear

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#84]
When cooking without electricity, all the meals that you have the right incredients but need electricity for are choosable like normaly, but nothing happens when you click on "Kochen". That itself works as attended, but new players might not understand what is going on. It would be best to either disable the recipes where one needs electricity, or to have a quick error message "Kann ohne Strom nicht gekocht werden" when clicking on "Kochen".

**Comment by marCOmics** [comment]
done AFAIK, also @Micky1503 added finer-grained error texts with the code review recently
