### ISSUE TITLE
Character-Choosing before Tutorial: Continue-button instead of Back-button 

### ISSUE THREAD

**Issue by Micky1503** [Spexify/emergenCity#92]
When you choose your character the first time right before the tutorial-dialogue, the button to continue is the "Back"-button, which does not really make sense. For the tutorial (not in general) this button should be changed to the "Continue"-button.

Edit: You can't choose a character from the lower rows.

ADDITIONALLY: Generally add a button that is a green Check-Button, which saves the changes. The original back button should cancel out the changes (while not in the tutorial)

**Comment by marCOmics** [comment]
done
